### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by oscaralmqvist** [oscaralmqvist/simsiam-pytorch#1]
- [ ] Add multiple datasets (voc, coco, cifar100)
- [ ] Add new transformations
- [ ] Fix hyperparameters
- [x] Add Wandb
- [ ] Write report
- [ ] Add linear classifier (missing in original paper?)
- [ ] RUN!
